name-template: v$NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION
categories:
  - title: 🔨 Improvements
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🚀 New Features
    label: Feature
change-template: '- #$NUMBER: $TITLE by @$AUTHOR'
template: |
  # Changes
  $CHANGES
  
