services:
  _defaults:
    public: true
  ps_sbu_privilege.repository.privilege_codetoto:
    class: 'PrestaShop\Module\SbuPrivilegeCode\Repository\PrivilegeCodeRepository'
    arguments:
      - '@doctrine.dbal.default_connection'
      - '%database_prefix%'
